# Лабораторная работа 2
# Встроенные типы обьектов в Python
**Гимбицкий Матвей** **14.03.2025**

# *Задание 1*

# Иерархическая модель типов встроенных объектов Python.

 Встроенные типы объектов делятся на:
 
Числа:


- Целые числа(`int`), неизменяемые
       
- числа с плавающей точкой(`float`), неизменяемые
      
- комплексные числа(`complex`), неизменяемые
   
- Булевый тип(`bool`) - наследуется от `int`, неизменяемые

Коллекции:

    
- Последовательности:
   
    - строки(`str`), неупорядоченные, неизменяемые.
         
    - списки(`list`), упорядоченные, изменяемые.
         
    - кортежи(`tuple`), упорядоченные, неизменяемые.
       
- Отображения:
   
    - словари(`dict`), неупорядоченные, изменяемые.
      
- Множества:
   
    - множества(`set`), неупорядоченные, изменяемые.


Пример литералов для создания обьекта:

- `42` - для `int`

- `3.14` - для `float`

- `1 + 1j` - для `complex`

- `True` , `False` - для `bool`

- `"Hello"` - для `str`

- `[1,2,3]` - для `list`

- `(1,2,3)` - для `tuple`

- `{'a': 1, 'b': 2}` - для `dict`

- `{1, 2, 3}` - для `set`
    

# Задание 2:
Проработайте материал лекций, представленный в файле
`2025_KM2_T2_Types.pdf`, разделы 2.1 – 2.12.

# Выполнение задания 2:

## Задание 2.1 

- 2.1 Понятие объекта. Атрибуты. Методы. Встроенные типы объектов

- 2.2 Встроенные типы объектов, представляющих числа
 
- 2.3 Встроенные типы последовательностей: str, list, tuple

- 2.4 Встроенный тип отображения: dict

- 2.5 Встроенный тип множества: set

- 2.6 Встроенный булевый тип

- 2.7 Изменяемые и неизменяемые встроенные типы объектов

- 2.8 Интерфейс объекта: операции и методы

- 2.9 Переменная

- 2.10 Выражение спискового включения

- 2.11 Форматированный вывод строк

- 2.12 Файловый объект


## 2.2 Встроенные типы объектов, представляющих числа

In [2]:
from decimal import Decimal
num1 = Decimal('10.5')
num2 = Decimal('3.2')       
print("Сумма:", num1 + num2)        
print("Разность:", num1 - num2)      
print("Произведение:", num1 * num2)     
print("Деление:", num1 / num2)        

Сумма: 13.7
Разность: 7.3
Произведение: 33.60
Деление: 3.28125


In [3]:
from fractions import Fraction
frac1 = Fraction(3, 4)  
frac2 = Fraction(1, 2)    
print("Сумма:", frac1 + frac2)          
print("Разность:", frac1 - frac2)  
print("Произведение:", frac1 * frac2) 
print("Деление:",frac1 / frac2)    

Сумма: 5/4
Разность: 1/4
Произведение: 3/8
Деление: 3/2


## 2.3 Встроенные типы последовательностей: str, list, tuple

In [4]:
S = 'spam'
print(S)
S = S[:1] + 'l' + S[2:]
print(S)  


spam
slam



- S[:1] — это срез строки, который берет все символы строки S до индекса 1 (не включая его). В данном случае это 's'.
- 'l' — это просто символ 'l', который мы хотим вставить в строку.
- S[2:] — это срез строки, который берет все символы, начиная с индекса 2 до конца строки. В данном случае это 'am'.

Для списка(`list`)

In [5]:
L = ['s', 'p', 'a', 'm']
L[1] = 'l'
print(L)  

['s', 'l', 'a', 'm']


Для кортеджа(`tuple`)

In [6]:
T = ('s', 'p', 'a', 'm')
T = T[:1] + ('l',) + T[2:]
print(T)  

('s', 'l', 'a', 'm')


## 2.4 Встроенный тип отображения: dict

In [7]:
personal_info = {
    "имя": "Матвей",
    "отчество": "Дмитриевич",
    "фамилия": "Гимбицкий",
    "возраст": 18,
    "место работы": "BSU",
    "адрес": "Минск, Беларусь",
    "email": "gimbitski.matvey@inbox.ru",
    "телефон": "+375297654321"
}
name = personal_info["имя"]
age = personal_info["возраст"]
email = personal_info["email"]
print(f"Имя: {name}, Возраст: {age}, Email: {email}")


Имя: Матвей, Возраст: 18, Email: gimbitski.matvey@inbox.ru


## 2.5 Встроенный тип множества: set

In [8]:
a='matttvvvveeeeeeeyy'
print(a)
a1=""
for i in a:
    if i not in a1:
        a1+=i
print(a1)

matttvvvveeeeeeeyy
matvey


## 2.8 Интерфейс объекта: операции и методы

Метод `count` возвращает количество вхождений подстроки в строке.

In [9]:
text = "hello world"
count_h = text.count("o")
print(count_h)

2


Метод `index` возвращает индекс первого вхождения подстроки в строке

In [10]:
index_h = text.index("o")
print(index_h)  

4


In [11]:
a = "  Привет, мир!    "
b= a.strip().upper().replace("МИР", "ВСЕЛЕННАЯ")
print(b)

ПРИВЕТ, ВСЕЛЕННАЯ!


Метод `append`:

In [12]:
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)  

[1, 2, 3, 4]


Метод append() добавляет элемент в конец списка.

Метод `extend`:


In [13]:
my_list = [1, 2, 3]
my_list.extend([4, 5, 6])
print(my_list) 

[1, 2, 3, 4, 5, 6]


Метод extend() добавляет элементы из итерируемого объекта (например, другого списка) в конец текущего списка.

Метод `insert`:

In [14]:
my_list = [1, 2, 3]
my_list.insert(1, 1.5)
print(my_list)  

[1, 1.5, 2, 3]


Метод insert() добавляет элемент по указанному индексу. Все элементы, находящиеся после этого индекса, сдвигаются вправо.

In [15]:
lst = ["123435", "11234453467789", "123"]
lst.sort(key=len) 
print(lst)


['123', '123435', '11234453467789']


In [16]:
for i in range (1,101):
    print(f"{i}=значение")

1=значение
2=значение
3=значение
4=значение
5=значение
6=значение
7=значение
8=значение
9=значение
10=значение
11=значение
12=значение
13=значение
14=значение
15=значение
16=значение
17=значение
18=значение
19=значение
20=значение
21=значение
22=значение
23=значение
24=значение
25=значение
26=значение
27=значение
28=значение
29=значение
30=значение
31=значение
32=значение
33=значение
34=значение
35=значение
36=значение
37=значение
38=значение
39=значение
40=значение
41=значение
42=значение
43=значение
44=значение
45=значение
46=значение
47=значение
48=значение
49=значение
50=значение
51=значение
52=значение
53=значение
54=значение
55=значение
56=значение
57=значение
58=значение
59=значение
60=значение
61=значение
62=значение
63=значение
64=значение
65=значение
66=значение
67=значение
68=значение
69=значение
70=значение
71=значение
72=значение
73=значение
74=значение
75=значение
76=значение
77=значение
78=значение
79=значение
80=значение
81=значение
82=значение
83=значение
84=значение
8



## 2.9 Переменная

In [17]:
a = [1, 2]
a.append(a)
a

[1, 2, [...]]

In [18]:
a={'one':1,'two':2}
a['three']=a;a

{'one': 1, 'two': 2, 'three': {...}}

In [19]:
a = [1, 2, 3]
x = a.copy()
x1 = a[:]
x2 = list(a)
print("Копия 1:", x)              
print("Копия 2:", x1)               
print("Копия 3:", x2)              

Копия 1: [1, 2, 3]
Копия 2: [1, 2, 3]
Копия 3: [1, 2, 3]


## 2.10 Выражение спискового включения

In [27]:
a = {x for x in range(10) if x % 2 == 1}
print(a)

{1, 3, 5, 7, 9}


In [24]:
import numpy as np
matrix_list = [[j + i * 8 for j in range(8)] for i in range(7)]
print("Матрица с использованием списковых включений:")
for row in matrix_list:
    print(row)
matrix_numpy = np.arange(56).reshape(7, 8)
print("\nМатрица с использованием numpy:")
print(matrix_numpy)

Матрица с использованием списковых включений:
[0, 1, 2, 3, 4, 5, 6, 7]
[8, 9, 10, 11, 12, 13, 14, 15]
[16, 17, 18, 19, 20, 21, 22, 23]
[24, 25, 26, 27, 28, 29, 30, 31]
[32, 33, 34, 35, 36, 37, 38, 39]
[40, 41, 42, 43, 44, 45, 46, 47]
[48, 49, 50, 51, 52, 53, 54, 55]

Матрица с использованием numpy:
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]]


In [ ]:
a = {}

for i in range(4):
    a[i] = {'a': i+5, 'b': i+10, 'c':i+15}
print(a)

{0: {'a': 5, 'b': 10, 'c': 15}, 1: {'a': 6, 'b': 11, 'c': 16}, 2: {'a': 7, 'b': 12, 'c': 17}, 3: {'a': 8, 'b': 13, 'c': 18}}


## 2.11 Форматированный вывод строк

In [ ]:
value = 1
print(f'Значение: {value=:<10}') 

Значение: value=1         


In [45]:
x = 10
y = 5
print(f'Результат: {x+y=:<10}')


Результат: x+y=15        


## 2.12 Файловый объект

In [ ]:
with open('example.txt', 'w') as file:
    file.write('Первая строка\n')
    file.write('Вторая строка\n')
    file.writelines(['Третья строка\n', 'Четвертая строка\n'])

with open('example.txt', 'r') as file:
    content = file.read()
    print('Содержимое файла:')
    print(content)

    
    file.seek(0)  
    print('Чтение построчно:')
    first_line = file.readline()
    print(first_line.strip()) 

    second_line = file.readline()
    print(second_line.strip())

    
    file.seek(0)  
    lines = file.readlines()
    print('Все строки в списке:')
    print([line.strip() for line in lines])  

Содержимое файла:
Первая строка
Вторая строка
Третья строка
Четвертая строка

Чтение построчно:
Первая строка
Вторая строка
Все строки в списке:
['Первая строка', 'Вторая строка', 'Третья строка', 'Четвертая строка']


# Задание 2.3
1 ошибка

In [47]:
print('\c \xc6')

\c Æ


<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
/var/folders/lp/_nklc76j0bb3fy5hnqjk1gsw0000gn/T/ipykernel_2312/1155648579.py:1: SyntaxWarning: invalid escape sequence '\c'
  print('\c \xc6')


Ошибка появляется потому что питон не распознает символ `c` после \ в качестве допустимого управляющего кода.Нужно использовать raw-строку

2 ошибка


In [48]:
str1= 'String'
str1[10]

IndexError: string index out of range

Индекс 10 выходит за пределы строки.Можно заполнить строку до нужной длины, указать существующий индекс или написать вывод об ошибке

3 ошибка

In [49]:
[1] + '1'

TypeError: can only concatenate list (not "str") to list

	
В выражении с операцией сложения + для последовательностей в качестве операндов могут быть использованы только объекты одного и того же типа. Нельзя использовать последовательности различных типов в операции сложения + из-за строгой типизации объектов в Python.

4 ошибка 

In [50]:
dict1['two']

NameError: name 'dict1' is not defined

Несуществующий ключ "two"

5 ошибка 

In [51]:
t = [1,2], {1:2}, {1,2}; 
t[0] = 0

TypeError: 'tuple' object does not support item assignment

Когда вы пытаетесь выполнить t[0] = 0, это приведет к ошибке, если t определен как кортеж, потому что кортежи являются неизменяемыми (immutable) в Python. Вы не можете изменять элементы кортежа после его создания.

6 ошибка 

In [52]:
{1, 'str', (1,)}.add([1])

TypeError: unhashable type: 'list'

Элементами множества могут являться только объекты неизменяемых типов: число, строка, кортеж.

7 ошибка

In [53]:
s = '+'.join('string'); s

print(s, s.find('-'))
s.index('-')

s+t+r+i+n+g -1


ValueError: substring not found

подстрока не содержится в строке поэтому python выдает ошибку

In [54]:
a = 1 # создание переменной
a, d

NameError: name 'd' is not defined

Чтобы переменную можно было использовать, ей обязательно должно быть присвоено значение. Использование переменной до того, как ей было присвоено значение, всегда приведет к ошибке.

In [55]:
print(abs(-1))
abs = 5
print(abs(-1))

1


TypeError: 'int' object is not callable

Ошибка возникает из-за того, что мы переопределяем встроенную функцию abs в Python, присваивая ей значение 5. После этого abs больше не ссылается на встроенную функцию, которая вычисляет абсолютное значение числа. Вместо этого она становится обычной переменной с целочисленным значением 5.